spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

app:
  frontend-url: ${FRONTEND_URL}
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:86400000}
  admin:
    email: ${APP_ADMIN_EMAIL}
    password: ${APP_ADMIN_PASSWORD}
    name: ${APP_ADMIN_NAME:GoRentals Admin}

logging:
  level:
    root: WARN
    com.rentit: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
